// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD1JNfa-NXcUMWHoKpUvg9SB0gdmvIWVQ',
    appId: '1:238065592747:web:61b403929316e59747caee',
    messagingSenderId: '238065592747',
    projectId: 'instantgram-69930',
    authDomain: 'instantgram-69930.firebaseapp.com',
    storageBucket: 'instantgram-69930.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBC65bEnOJbBiQbRtiD5MU_EaK55rGIlg',
    appId: '1:238065592747:android:91764f55f141617f47caee',
    messagingSenderId: '238065592747',
    projectId: 'instantgram-69930',
    storageBucket: 'instantgram-69930.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBgLUUX9yhJuj4v97hhP8HXk7VHpEnw6s',
    appId: '1:238065592747:ios:a0c04b5d27cda4a647caee',
    messagingSenderId: '238065592747',
    projectId: 'instantgram-69930',
    storageBucket: 'instantgram-69930.appspot.com',
    iosClientId: '238065592747-t5mhbtlu4qujr3vd5mooq31nsvpo6ip2.apps.googleusercontent.com',
    iosBundleId: 'com.example.instantgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBgLUUX9yhJuj4v97hhP8HXk7VHpEnw6s',
    appId: '1:238065592747:ios:a0c04b5d27cda4a647caee',
    messagingSenderId: '238065592747',
    projectId: 'instantgram-69930',
    storageBucket: 'instantgram-69930.appspot.com',
    iosClientId: '238065592747-t5mhbtlu4qujr3vd5mooq31nsvpo6ip2.apps.googleusercontent.com',
    iosBundleId: 'com.example.instantgram',
  );
}
